- applications/accounts/deploy/resources/realm.json
- applications/accounts/deploy/values.yaml
removed the www kc client and made client web-client public
> removed the www kc client and made client web-client public

- applications/common/common/controllers/sentry_controller.py
- libraries/cloudharness-common/cloudharness/applications.py
- libraries/cloudharness-common/cloudharness/utils/config.py
- libraries/cloudharness-common/tests/test_applications.py
> #33 High level configuration api

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
> #46 increase proxy-body-size of Ingress server to 10M

- utilities/cloudharness_utilities/build.py
- utilities/cloudharness_utilities/helm.py
- utilities/harness-deployment
> #50 Add parameter to specify included applications

- utilities/cloudharness_utilities/build.py
- utilities/cloudharness_utilities/deployment-configuration/codefresh-build-template.yaml
- utilities/harness-deployment
> #52 add namespace and domain to build args so it can be used during building of the images

- applications/accounts/deploy/resources/realm.json
- applications/argo/deploy/values.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-gatekeepers.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/tls-secret.yaml
- utilities/cloudharness_utilities/helm.py
- utilities/harness-deployment
> #78 Add option to disable tls

- applications/events/deploy/resources/broker/init.sh
> #76 chore: added create kafka cluster on init

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/_helpers.tpl
> #83 removed default reference to accounts application

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/certs/letsencrypt.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
> feature/86 Change ClusterIssuer Letsencrypt to support multiple of them in the same GC cluster

- applications/events/deploy/templates/roles.yml
fix to support multiple instances of MNP in one cluster
> #94 chore: changed ClusterRole to Cluster and added namespace

- libraries/cloudharness-common/cloudharness/utils/config.py
- libraries/cloudharness-common/cloudharness/utils/env.py
- libraries/cloudharness-common/cloudharness/workflows/argo.py
- utilities/cloudharness_utilities/codefresh.py
- utilities/cloudharness_utilities/constants.py
- utilities/harness-codefresh
> Feature/96 Support multiple paths in codefresh generate script

- libraries/cloudharness-common/cloudharness/events/client.py
> #176 chore: add a more elegant way to create topics, don't raise errors in case a topic exists

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
> #200 Add command and args specification on auto deployment

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-services.yaml
> #203 Add target port for auto-services

- libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
Tested manually since this was rejecting the connection to my keycloak within minikube from the backend running on localhost.
> Adding auth to SERVER_URL

- utilities/cloudharness_utilities/build.py
> #211 Improve build error messaging

- infrastructure/base-images/cloudharness-base/Dockerfile
- utilities/cloudharness_utilities/application-templates/server/backend/Dockerfile
> #196 Remove duplicated copy

- applications/accounts/deploy/values.yaml
> #226 chore: accounts set max heap size

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
> #253 add pod affinity to auto deployments by volume usage

- libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> #251 chore: add CH_CURRENT_USER_ID as an env var to set the current user during development

- utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
> #279 add proxy services for main app

- libraries/cloudharness-common/cloudharness/utils/secrets.py
- utilities/cloudharness_utilities/codefresh.py
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-secrets.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/configmap.yaml
- utilities/harness-deployment
update the secrets usage from:
```
get_secret("mnp-checkout", "stripe-public-key")
```
to
```
get_secret("stripe-public-key")
```
also no need to do a b64decode anymore
e.g.
```
base64.b64decode(get_secret("mnp-checkout", "stripe-public-key")).decode("ascii")
```
needs to be replaced by
```
get_secret("stripe-public-key")
```
> #240 chore: implemented secrets through mounting instead of env vars and make sure secret values aren't in the allvalues.yaml

- libraries/cloudharness-common/cloudharness/events/client.py
…s & refrased some error messages
> #297 chore: add create topic to produce when kafkatimeout error occurs & refrased some error messages

- utilities/cloudharness_utilities/codefresh.py
- utilities/harness-deployment
> #310 expandable deployment pipelines implemented

- libraries/cloudharness-common/cloudharness/applications.py
- libraries/cloudharness-common/cloudharness/utils/server.py
> #322 Generic backend api error handling improved

- applications/jupyterhub/Dockerfile
- applications/jupyterhub/deploy/values.yaml
- applications/jupyterhub/src/harness_jupyter/harness_jupyter/jupyterhub.py
example:
```
harness:
jupyterhub:
spawnerExtraConfig:
cpu_guarantee: 1.6
cpu_limit: 3
mem_guarantee: 4G
mem_limit: 8G
```
> Feature/328: Jupyterhub enable cpu/mem resources per application

- applications/jupyterhub/deploy/resources/hub/jupyterhub_config.py
- applications/jupyterhub/deploy/resources/hub/z2jh.py
- applications/jupyterhub/src/harness_jupyter/harness_jupyter/jupyterhub.py
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
- utilities/cloudharness_utilities/deployment-configuration/value-template.yaml
- utilities/cloudharness_utilities/helm.py
> #333 support for multi-level domains and aliases

- applications/jupyterhub/deploy/resources/hub/z2jh.py
- libraries/cloudharness-common/cloudharness/utils/__init__.py
- utilities/cloudharness_utilities/utils.py
Moved to collections.abc in py3.3+
Reference: https://docs.python.org/3/library/collections.abc.html
> fix: update collection related imports

- .gitignore
- utilities/tests/resources/applications/events/deploy/values-prod.yaml
- utilities/tests/resources/applications/events/deploy/values.yaml
- utilities/tests/test_helm.py
Closes #347.
Added test coverage and looks like the precedence overriding works as expected.
> #347 add test coverage for values.yaml precedence

- utilities/harness-deployment
> #263 chore fix -e parameter description

- applications/accounts/deploy/templates/api-user-secret.yaml
- applications/accounts/deploy/values.yaml
- applications/jupyterhub/deploy/templates/hub/deployment.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
- utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-secrets.yaml
> #361 chore: use CH secrets for api acocunt secret, use a random string for nullable secrets default value

- utilities/cloudharness_utilities/codefresh.py
> #387 chore: add auto secrets to codefresh.yaml only if the secret has a value defined in the values.yaml

- applications/accounts/deploy/values.yaml
- applications/accounts/scripts/create_api_user.sh
- libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> #395 chore: set accounts admin api username to admin_api

- .github/pull_request_template.md
Closes #404
Implemented solution: see [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository). The template has been added to the .github directory in the root of the project
How to test: the template used for this PR  will appear only after merging this to the default branch on all prs.
> #404 Pull request template

- applications/argo/deploy/charts/values.yaml
Closes #423
Implemented solution: change the executor from docker to the new emissary 
How to test this PR: run a deployment with argo on google cloud and run any workflow. An option is to use the argo-ui interface on argo.DOMAIN
> #423 change the argo executor

- libraries/cloudharness-common/cloudharness/auth/keycloak.py
- libraries/cloudharness-common/requirements.txt
Closes #457 
Implemented solution: remove cache from CH keycloak library
How to test this PR: no need
> #457 feature removed the cached functions from keycloak

- applications/notifications/server/requirements.txt
- applications/notifications/server/setup.py
- libraries/cloudharness-common/cloudharness/auth/keycloak.py
- libraries/cloudharness-common/requirements.txt
- libraries/cloudharness-common/setup.py
Fixes #460 , #465 -- included on release/1.0.0 as an hotfix.
Notifications breaks without this fix
> Release/1.0.0 to develop -- hotfixes

- docs/applications/development/workflows-api.md
- libraries/cloudharness-common/cloudharness/workflows/argo.py
Closes #517 
Implemented solution: Status filter passed to the argo api. Other parameters passed through
How to test this PR: example usage: https://github.com/OpenSourceBrain/OSBv2/blob/8b2d97d5c1f84c973066a82ab3503b187f104977/applications/workspaces/server/workspaces/service/model_service.py#L251
> #517 Implement workflows filter

- tools/harness-deployment
> #503 merge fix

- infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/services/user.py
Closes #562 
Implemented solution: add Member creation of new User creation
How to test this PR: create a new User in KC and check if there is a Member record in the database
> #562 fix: create a Member record for new KC users

- docs/README.md
- docs/tutorials/simple-date-clock-application.adoc
This PR proposes a small tutorial about how to bootstrap/modify a simple webapp using cloud-harness.
The tutorial is a little bit naive right now as I'm still learning all about the framework and there is probably mistakes in the document. Feel free to point the mistakes and to propose suggestions, I'll try to integrate them :)
> Add tuto about a simple clock/date webapp creation

- .gitignore
- applications/events/Dockerfile
- applications/events/deploy/charts/.helmignore
- applications/events/deploy/charts/Chart.yaml
- applications/events/deploy/charts/README.md
- applications/events/deploy/charts/index.yaml
- applications/events/deploy/charts/templates/NOTES.txt
- applications/events/deploy/charts/templates/_helpers.tpl
- applications/events/deploy/charts/templates/configmap.yaml
- applications/events/deploy/charts/templates/configmap_fromValues.yaml
- applications/events/deploy/charts/templates/deployment.yaml
- applications/events/deploy/charts/templates/hpa.yaml
- applications/events/deploy/charts/templates/ingress.yaml
- applications/events/deploy/charts/templates/networkpolicy-egress.yaml
- applications/events/deploy/charts/templates/networkpolicy-ingress.yaml
- applications/events/deploy/charts/templates/secret.yaml
- applications/events/deploy/charts/templates/service.yaml
- applications/events/deploy/charts/templates/serviceaccount.yaml
- applications/events/deploy/charts/values.yaml
- applications/events/deploy/resources/broker/init.sh
- applications/events/deploy/templates/configmap.yaml
- applications/events/deploy/values-dev.yaml
- applications/events/deploy/values-test.yaml
- applications/events/deploy/values.yaml
- deployment/codefresh-test.yaml
Closes #625
Implemented solution: Added chart for kafka-ui and replaced monitor with the new ui on events.* 
How to test this PR: On a deployment, go to events.DOMAIN and use it. E2e tests are covering the main page.
> #625 Enhance events ui

- deployment-configuration/helm/templates/certs/letsencrypt.yaml
Closes #666
Implemented solution: name of issuer secret changed
How to test this PR: create a remote deployment and check that certificates are issued correctly
> #666 change issuer certificate name

- docs/dev.md
This PR proposes a documentation for CloudHarness developers, to help to locate and understand how the different part of the projects are working together.
The CloudHarness code base can be really complicated to understand well in the first place, there is a lot of sub-projects and libraries. This documentation aims developers to help them navigate through the source code and understand some concepts in order to be able to fix bugs or extend the various tools present in CloudHarness to implement new features quickly.
> Add dev specific doc for CloudHarness CLI tools

- .github/pull_request_template.md
Closes [CH-111](https://metacell.atlassian.net/browse/CH-111)
The template file has been changed
Cannot test before merging, but no need to as no code has been touched.
This text matches the new template.
[CH-117]: https://metacell.atlassian.net/browse/CH-117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CH-111]: https://metacell.atlassian.net/browse/CH-111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CH-111 chore: update pull request template

- tools/deployment-cli-tools/ch_cli_tools/codefresh.py
Closes [CH-166](https://metacell.atlassian.net/browse/CH-166)
[CH-166]: https://metacell.atlassian.net/browse/CH-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CH-166 fix syntax issue

- deployment-configuration/helm/templates/auto-secrets.yaml
> CH-170 fix secrets upgrade

- applications/jupyterhub/src/harness_jupyter/harness_jupyter/jupyterhub.py
> fix(MC-193): too many calls to apply_node_selectors

- deployment/codefresh-test.yaml
- libraries/cloudharness-common/cloudharness/auth/user_attributes.py
- libraries/cloudharness-common/cloudharness/infrastructure/k8s.py
- libraries/models/cloudharness_model/models/backup_config.py
- libraries/models/cloudharness_model/models/deployment_auto_artifact_config.py
- libraries/models/cloudharness_model/models/deployment_auto_artifact_config_all_of.py
- tools/deployment-cli-tools/ch_cli_tools/codefresh.py
- tools/deployment-cli-tools/tests/test_helm.py
https://metacell.atlassian.net/browse/CH-21
> CH-21 fix JupyerHub dependency on accounts
