MetaCell/cloud-harness

utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml
utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-volumes.yaml

option for adding a persistent volume to an app
this is how it can be configured:
```
deployment:
auto: true
port: 8080
volume:
name: workspaces-images
size: 4G
mountpath: /usr/src/app/workspaces/static/workspaces
```

chore: add persistent volume option to auto deploy apps

---

utilities/cloudharness_utilities/codefresh.py
utilities/cloudharness_utilities/constants.py
utilities/cloudharness_utilities/deployment-configuration/README.md
utilities/cloudharness_utilities/deployment-configuration/codefresh-publish-template.yaml
utilities/cloudharness_utilities/deployment-configuration/codefresh-template-dev.yaml
utilities/cloudharness_utilities/deployment-configuration/codefresh-template-prod.yaml
utilities/cloudharness_utilities/utils.py
utilities/harness-deployment

Closes #109 
After this pr, the codefresh pipeline must be changed to point to either 
- deployment/codefresh-dev.yaml
- deployment/codefresh-prod.yaml
Also check your application deployment-configuration: codefresh-template.yaml splits into 
- codefresh-template-dev.yaml
- codefresh-template-prod.yaml
The content must be adapted from the content inside codefresh-template-dev.yaml and the current codefresh-template.yaml

#109 codefresh dev and production deployment generation implemented

---

utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-database.yaml
utilities/cloudharness_utilities/deployment-configuration/value-template.yaml
utilities/cloudharness_utilities/helm.py

First phase of centralizing database management
implements: mongo, postgres and neo4j database pod/service creation
add new default settings in value-template.yaml for use in app values.yaml:
```
database:
auto: false
name:
type:
size: 1Gi
user: mnp
pass: metacell
mongo:
image: mongo:latest
ports:
- name: http
port: 27017
postgres:
image: postgres:latest
initialdb: cloudharness
ports:
- name: http
port: 5432
neo4j:
image: neo4j:latest
memory:
size: 256M
pagecache:
size: 64M
heap:
initial: 64M
max: 128M
dbms_security_auth_enabled: "false"
ports:
- name: http
port: 7474
- name: bolt
port: 7687
resources:
requests:
memory: "512Mi"
cpu: "200m"
limits:
memory: "2Gi"
cpu: "1000m"
```

Feature/135: Centralize database management phase 1

---

utilities/cloudharness_utilities/deployment-configuration/helm/templates/ingress.yaml
utilities/cloudharness_utilities/deployment-configuration/values-template.yaml
utilities/cloudharness_utilities/helm.py

Closes #159.
To configure the main address in the application now edit `mainapp` value in `values-template.yaml`.
For instance the values .yaml
```yaml
mainapp: myapp
domain: cloudharness.org
apps:
myapp:
harness:
name: myapp
subdomain: my
domain: www.myapp.org
```
Will set "myapp" ingress to the following domains:
* cloudharness.org
* my.cloudharness.org
* www.myapp.org

#159 fix main ingress assignment

---

utilities/cloudharness_utilities/application-templates/base/api/openapi.yaml
utilities/cloudharness_utilities/application-templates/base/deploy/values.yaml
utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml

livenessProbe and readinessProbe are optional for the application user.
If either of them is specified, a httpGet probe is defined and the user must specify a path for it.
Optionally, she can also specify periodSeconds or initialDelaySeconds to further adjust the probes to the characteristic of the app or environment.
**Manual testing**
* Create application with `harness-application dbapp -t webapp -t db-postgres`
* Choose different configuration for liveness and readiness configuration & test if they are reflected in K8s deployment after helm upgrade

#155 Add liveness and readiness probe

---

utilities/cloudharness_utilities/deployment-configuration/codefresh-template-prod.yaml

With this change when DEPLOYMENT_PUBLISH_TAG is not defined on production pipeline we don't do the registry and git tagging

Optional tagging on stage/production

---

libraries/cloudharness-common/cloudharness/applications.py
libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py

This refactoring improves clarity in auth initialization code and reduces the calls to keycloak by caching the public key
Closes #190

#190 refactor auth api

---

applications/accounts/deploy/resources/realm.json

**Manual testing with minikube:**
* Delete existing cluster
* Start new cluster
* Run `harness-deployment . -l -b -dtls` and install helm chart
* Check in Keycloak UI if ssl required is set to "none"
Repeat procedure but without "-dtls" flag and check if ssl required is set to "external requests".
**Important to know:**
When I enabled/disabled -dtls on an existing cluster, changes won't be reflected, since the realm.json is only imported at startup of accounts pod and only if it wasn't already imported. While one can manually delete keycloak realm and then restart the accounts pod, the tls option is used in many different templates and on first sight it seems that e.g. ingress controller must be restarted as well. **This is not done automatically after deploying the modified helm chart!** …

#186 Don't require TLS in Keycloak if TLS is deactivated

---

utilities/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml

remove subpart from the configmap mount to enable auto refresh, see https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

#317 chore: remove subpart from the configmap mount 

---

utilities/cloudharness_utilities/skaffold.py

For buildkit set `ssh:default` to allow private repo to be cloned in a docker file
see https://docs.docker.com/develop/develop-images/build_enhancements/#using-ssh-to-access-private-data-in-builds for more info

#356 ssh:default support for docker buildkit builds to support cloning of private git repos

---

docs/applications/development/backend-development.md
libraries/cloudharness-common/README.md
libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
libraries/cloudharness-common/cloudharness/middleware/__init__.py
libraries/cloudharness-common/cloudharness/middleware/django.py
libraries/cloudharness-common/cloudharness/middleware/flask.py
libraries/cloudharness-common/cloudharness/utils/server.py
libraries/cloudharness-common/tests/test_middleware.py

Remove Flask dependency from CH Keycloak AuthClient
Closes #401 
Implemented solution:  implement ch middleware for Flask and Django to set/get the ch application state. Refactored ch kc authentication to disconnect it from Flask
How to test: ...
- [x ] All the linked issues are assigned

#401 implement ch middleware for Flask and Django to set/get the ch application state. Refactored ch kc authentication to disconnect it from Flask

---

tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-deployments.yaml

Fixes #384
Implemented solution: the secret must be applied not only on deployments with a hard dependency on accounts, but also on accounts itself, as it is used to initialize the user in the first run.
How to test this PR: run a deployment and verify that inside accounts the path /opt/cloudharness/resources/auth/api_user_password exists

#384 fix: mount secret also on accounts pod

---

applications/argo/deploy/charts/values.yaml

Closes #423
Implemented solution: The emissary executor cannot guess the command from the docker image,
so causing troubles on preexisting tasks. Changing to pns.
How to test this PR: run an argo workflow without a command set explicitly from the argo-ui.

#423 change argo executor to pns

---

libraries/cloudharness-common/cloudharness/auth/keycloak.py

Closes #449 
Implemented solution: add the create/update groups methods and add/remove user from groups methods to AuthClient
```
from cloudharness.auth import AuthClient
ac = AuthClient()
ac.create_group({"name":"New Group"})
```
then check in Keycloak groups if the New Group was created

#449 feature: add keycloak group support to AuthClient

---

tools/cloudharness_utilities/codefresh.py
tools/tests/test_codefresh.py

Fixes #427 issue with codefresh paths
Implemented solution: fixed the relative paths for build context
How to test this PR: run `harness-deployment ... -e dev` and run generated build spec on codefresh.

#427 Fix codefresh files

---

tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-volumes.yaml

Closes #471 
Implemented solution: added check if the key `auto` exists and improved the auto boolean check

#471 fixes volume creation for volume objects without the auto key

---

applications/samples/deploy/values.yaml
tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-gatekeepers.yaml

Closes #418 
Implemented solution: added a checksum from the configuration to force pod restart -- see https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
How to test this PR: The simplest way to test is to make a local deployment from `harness-deployment . -i samples ...` and play with samples/values.yaml to change the configuration

#418 Force restart of gatekeeper on conf change

---

.gitignore
docs/build-deploy/environments.md
tools/cloudharness_utilities/codefresh.py
tools/cloudharness_utilities/deployment-configuration/codefresh-template-dev.yaml
tools/cloudharness_utilities/deployment-configuration/codefresh-template-prod.yaml
tools/cloudharness_utilities/helm.py
tools/harness-deployment
tools/tests/resources/applications/myapp/deploy/values-dev.yaml
tools/tests/resources/applications/myapp/deploy/values-test.yaml
tools/tests/resources/deployment-configuration/codefresh-template-dev.yaml
tools/tests/resources/deployment-configuration/codefresh-template-test.yaml
tools/tests/test_codefresh.py
tools/tests/test_helm.py

Closes #444
Implemented solution: can specify `harness-deployment -e env1-env2`
How to test this PR: Run `harness-deployment -e dev-prod`. A pipeline file deployment/codefresh-dev-prod.yaml is created.
Values in there and in deployment/values.yaml will contain the values from the variuous *-dev and *-prod configuration files

#444 implement multiple environments functionality

---

tools/cloudharness_utilities/codefresh.py
tools/tests/resources/deployment-configuration/codefresh-template-dev.yaml
tools/tests/test_codefresh.py

Closes #499
Implemented solution: the issue was in the way that the default templates were used at every step while scanning the directory: that was causing the default template to be used while scanning in the .overrides directory (that's why the bug was not appearing for deployments without overrides)
How to test this PR: Override `deployment-configuration/codefresh-template-dev.yaml` and run `harness-deployment ... -e dev` and check the result. At least one application must be overridden in order for the fix to be evident.

#499 Fix codefresh templates overriding

---

tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-database-mongo-backup.yaml
tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-database-postgres-backup.yaml

Closes #508 
Implemented solution: updated v1Beta spec to v1 in CronJob templates
How to test this PR: enable backups on deployment-configuration/values.yaml --> `backup/active=true`

#508 update k8s spec for cron jobs

---

docs/applications/development/workflows-api.md
libraries/cloudharness-common/cloudharness/workflows/operations.py
libraries/cloudharness-common/tests/test_workflow.py

Closes #505 
Closes #506 
Closes #512 
**Implemented solution**
#506: Readonly volumes can be added with the `:ro` at the end of the shared_directory string.
#505: Multiple values are allowed for `pod_context` as list or tuple  https://github.com/MetaCell/cloud-harness/blob/6bb7a96ef9b2e3530696ec93488d2f1c2258ca90/libraries/cloudharness-common/tests/test_workflow.py#L236
#512 pod contexts are added automatically for volumes specified as shared_directory
How to test this PR:
Unit tests are covering the functionality.
Create an operation like
```
op = operations.ParallelOperation('test-parallel-op-', (tasks.PythonTask('p1', f), tasks.PythonTask('p2', f)),
pod_context=(
operations.PodExecutionContext('a', 'b'), 
operations.PodExecutionContext('c', 'd', required=True), …
```

Workflows and volumes enhancements

---

libraries/cloudharness-common/cloudharness/auth/keycloak.py

Closes #525
Implemented solution: added or {}
How to test this PR: create a KC user and try setting the attributes throught the ch auth api

#525 fixes None type error when setting an attribute on an user without attributes

---

applications/accounts/Dockerfile
applications/accounts/admin-event-listener/.gitignore
applications/accounts/admin-event-listener/README.md
applications/accounts/admin-event-listener/ear-module/pom.xml
applications/accounts/admin-event-listener/jar-module/pom.xml
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventKafkaProducer.java
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventListenerProvider.java
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventListenerProviderFactory.java
applications/accounts/admin-event-listener/jar-module/src/main/resources/META-INF/jboss-deployment-structure.xml
applications/accounts/admin-event-listener/jar-module/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
applications/accounts/admin-event-listener/pom.xml

Closes #533 
Implemented solution: java kafka event listener
How to test this PR: install the feature and enable the metacell event listener in the Keycloak events configuration (see Events Config tab of the Keycloak admin interface)
- [x ] From the issue and the current PR it is explicitly stated how to test the current change

#533 feature: keycloak / accounts add admin interface kafka publisher

---

applications/accounts/Dockerfile
applications/accounts/admin-event-listener/.gitignore
applications/accounts/admin-event-listener/README.md
applications/accounts/admin-event-listener/ear-module/pom.xml
applications/accounts/admin-event-listener/jar-module/pom.xml
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventKafkaProducer.java
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventListenerProvider.java
applications/accounts/admin-event-listener/jar-module/src/main/java/us/metacellllc/admineventlistenerprovider/provider/AdminEventListenerProviderFactory.java
applications/accounts/admin-event-listener/jar-module/src/main/resources/META-INF/jboss-deployment-structure.xml
applications/accounts/admin-event-listener/jar-module/src/main/resources/META-INF/services/org.keycloak.events.EventListenerProviderFactory
applications/accounts/admin-event-listener/pom.xml
tools/cloudharness_utilities/application-templates/django-app/README.md
tools/cloudharness_utilities/application-templates/django-app/deploy/values.yaml
tools/harness-application
tools/harness-generate

Closes #532 
Implemented solution: set secure to true and create default uri-role-mappings
How to test this PR: create a sample application and deploy it in your minikube and try to access the `/admin/` page

Feature/532 Django app configuration to enable keycloak gatekeeper integration

---

tools/cloudharness_utilities/codefresh.py
tools/cloudharness_utilities/deployment-configuration/codefresh-template-dev.yaml
tools/cloudharness_utilities/deployment-configuration/codefresh-template-prod.yaml
tools/harness-deployment
tools/tests/test_codefresh.py

Closes #548 
Implemented solution: the command is now automatically generated by the script looking at the paths and included apps
How to test this PR: remove deployment-configuration/codefresh-dev.yaml from your solution and run harness-deployment ... -e dev. Check deployment/codefresh-dev.yaml to check that everything is ok

#548 dynamic generation of codefresh prepare cmd

---

tools/cloudharness_utilities/codefresh.py
tools/cloudharness_utilities/constants.py
tools/cloudharness_utilities/preprocessing.py

Fixes #548 regression with overriden files (dockerfile included)
Implemented solution: .overrides removed from the generated paths
How to test this PR: run harness-deployment ... -e dev in a deployment with overridden applications and check that .overrides is not included in the codefresh-dev.yaml file

#548 fix .overrides directory being included in cf

---

tools/cloudharness_utilities/application-templates/django-app/api/templates/main.jinja2

Closes #563
Implemented solution: update the Jinja2 library to generate the correct function calls
How to test this PR: run genapi.sh on an openapi.yaml file

#563 fix: crashing openapi backend generator for route based params

---

infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/settings.py

Closes #561 
Implemented solution: add CSRF_TRUSTED_ORIGINS setting
How to test this PR: install a CH Django based app, go to the admin and create a new record. If no CSRF failure then everything is correct

#561 fix: add CSRF_TRUSTED_ORIGINS to fix CSRF admin issue

---

tools/cloudharness_utilities/openapi.py

Closes #571 
Implemented solution: ` added get_dependencies()`
How to test this PR: `harness-application -t webapp testapp`

#571 fix: added get_dependencies() call to generator methods to check & get the dependencies for openapi

---

tools/cloudharness_utilities/deployment-configuration/helm/templates/auto-gatekeepers.yaml

Closes #573 
Implemented solution: changed the value in the auto-gatekeeper template 
How to test this PR: open a page with a gatekeeper and check in the chrome console if document.cookie has `kc-access`

#573 default gk http-only-cookie false

---

tools/cloudharness_utilities/codefresh.py

Closes #577
Implemented solution: : replaced with __ see https://codefresh.io/docs/docs/new-helm/using-helm-in-codefresh-pipeline/ -- "If a variable already contains a _ (underscore) in its name, replace it with __ (double underscore)."
How to test this PR: in a deployment with secrets check that _ custom values in the deployment step are replaced with __ like 
```
deployment:
stage: deploy
type: helm
working_directory: ./${{CF_REPO_NAME}}
title: Installing chart
arguments:
helm_version: 3.6.2
chart_name: deployment/helm
release_name: '${{NAMESPACE}}'
kube_context: '${{CLUSTER_NAME}}'
namespace: '${{NAMESPACE}}'
chart_version: '${{CF_BUILD_ID}}'
cmd_ps: --wait --timeout 600s
custom_value_files:
- ./deployment/helm/values.yaml
custom_values:
- …
```

#577 fix codefresh issue with _: replace _ with __

---

tools/cloudharness_utilities/application-templates/django-app/api/templates/main.jinja2

Closes #589 
Implemented solution: 
- Updates jinja template with correct syntax
- Run genapi.sh and check if it successfully generates the main.py file

#589 fix: Fix main.jinja2 template

---

libraries/cloudharness-common/cloudharness/auth/keycloak.py

Closes #632 
Implemented solution: added param `brief_representation` (default True) to the get user / get group , to retrieve the group details (incl. the attributes) set the param to False 
```python
from cloudharness.auth.keycloak import AuthClient
ac=AuthClient()
ac.get_users(brief_representation=False)
```
- [x ] From the issue and the current PR it is explicitly stated how to test the current change

#632 feat: add switch to retrieve group attributes

---

tools/deployment-cli-tools/ch_cli_tools/skaffold.py

Closes #628 
Implemented solution: added justMyCode=False flag to vscode debug configuration
How to test this PR: debug with vscode and put a breakpoint on library code.

#628 justMyCode added

---

applications/jupyterhub/src/harness_jupyter/harness_jupyter/jupyterhub.py

Closes #635 
Implemented solution: added a "generic" Pod Spawn Exception to CH jupyterhub.py that is catched and raised again instead of the generic catch all log and continue exception
- import PodSpawnException from harness_jupyter jupyterhub
- raise this exception

#635 feat: add user defined exception for use for general pod spawn errors

---

applications/jupyterhub/README.md
applications/jupyterhub/deploy/templates/image-puller/_helpers-daemonset.tpl

Closes #657 
Implemented solution: add loop over CH tasks to pre puller helper template
How to test this PR: run the deployment (helm) in dry-run debug mode and check the generated output JH image puller extraImages

#657 chore: add support for auto pulling CloudHarness tasks onto JupyterHub nodes with the JH prepuller

---

infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/migrations/0001_initial.py
infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/models.py
infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/services/auth.py
infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/services/user.py

Closes #688
Implemented solution: added a service function and db index
```
from cloudharness_django.services.user import get_user_by_kc_id
get_user_by_kc_id(kc_id)
```

#688 add django user service function

---

libraries/cloudharness-common/cloudharness/sentry/__init__.py

Closes CH-123
Implemented solution: changed cloudharness api to pass through sentry_sdk parameters 
How to test this PR: testing on a project (ask @filippomc)

CH-123 add parameters to Sentry init

---

deployment-configuration/helm/templates/ingress.yaml
deployment-configuration/helm/values.yaml
docs/ingress-domains-proxies.md

Closes [CH-124](https://metacell.atlassian.net/browse/CH-124)
Implemented solution: added `use-forwarded-headers` annotation to the ingress default template.
How to test this PR: deploy anche check that `use-forwarded-headers` is set in the cloudharness-ingress Ingress
[CH-124]: https://metacell.atlassian.net/browse/CH-124?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-124 add forwarded headers configuration

---

docs/applications/dependencies.md
tools/deployment-cli-tools/ch_cli_tools/codefresh.py
tools/deployment-cli-tools/ch_cli_tools/skaffold.py

Follows up from #720, relates to CH-37
The paths were not correctly relativized when used inside a top level app.
Also codefresh paths needed fix.
Implemented solution: fixed paths
How to test this PR: same as #720

Git clone functionality fixes

---

deployment-configuration/codefresh-template-stage.yaml

Closes CH-122
Implemented solution: fixed deployment-configuration template mistake
How to test this PR: create a staging deployment and run on codefresh

CH-122 fix stage template

---

docs/dev.md
infrastructure/base-images/cloudharness-frontend-build/Dockerfile
libraries/cloudharness-utils/cloudharness_utils/constants.py
test/test-e2e/Dockerfile

Closes CH-118
Implemented solution: The version has been updated in the CLOUDHARNESS_FRONTEND_BUILD image, which should be used a a dependency to build other node applications.
How to test this PR: Automated tests are enough here as the some images won't build if the image is not found

Update node version

---

deployment-configuration/helm/templates/auto-database.yaml
deployment-configuration/helm/templates/auto-deployments.yaml

Closes [CH-137](https://metacell.atlassian.net/browse/CH-137)
Added the namespace to the `usesvolume` labels and pod affinity label selectors.
... 
Run
`harness-deployment . -i samples -n <whatever>`
Move to `deployment/helm` and run
`helm template --debug . > tmp.yaml`
`tmp.yaml` should show that the `usesvolume` labels and selectors will have `-<whatever>` appended.
...
[CH-137]: https://metacell.atlassian.net/browse/CH-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-137 Add namespace to usesvolume labels and pod affinity selectors

---

application-templates/django-app/api/templates/main.jinja2
application-templates/webapp/frontend/src/App.tsx
application-templates/webapp/frontend/vite.config.ts

Closes [CH-45](https://metacell.atlassian.net/browse/CH-45)
Updated django main template to handle both auth header and auth cookie as well as fix some linting issues
... 
Use `harness-application` to create a new django application and run `genapi.sh` inside the created `api` folder
...
[CH-45]: https://metacell.atlassian.net/browse/CH-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-45 Update django main file template to handle both auth header and cookie

---

deployment-configuration/helm/templates/auto-gatekeepers.yaml

Closes [CH-163](https://metacell.atlassian.net/browse/CH-163)
Updated the gogatekeeper image from 1.3.8 to 2.14.3.
A small teak was necessary because `enable-default-deny: true` is not allowed anymore when "/*" rule is set
Can be tested from the test depoyment
[CH-163]: https://metacell.atlassian.net/browse/CH-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-163 Gatekeeper version update

---

deployment-configuration/codefresh-template-dev.yaml
deployment-configuration/codefresh-template-prod.yaml
deployment-configuration/codefresh-template-stage.yaml
deployment-configuration/codefresh-template-test.yaml
deployment/codefresh-test.yaml
tools/deployment-cli-tools/ch_cli_tools/codefresh.py

Closes [CH-166](https://metacell.atlassian.net/browse/CH-166)
Changed the syntax of the post-main-clone step from list to dict, in the codefresh templates and in the generating script.
Generate a new pipeline for a project that uses cloudharness and check that the post-main-clone step steps are defined as a dict
[CH-166]: https://metacell.atlassian.net/browse/CH-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-166 fix codefresh post-clone

---

applications/workflows/server/workflows_api/service/workflow_service.py
docs/applications/development/workflows-api.md
libraries/cloudharness-common/cloudharness/utils/__init__.py
libraries/cloudharness-common/cloudharness/workflows/__init__.py
libraries/cloudharness-common/cloudharness/workflows/argo_service.py
libraries/cloudharness-common/cloudharness/workflows/operations.py
libraries/cloudharness-common/cloudharness/workflows/tasks.py
libraries/cloudharness-common/tests/test_applications.py
libraries/cloudharness-common/tests/test_env.py
libraries/cloudharness-common/tests/test_workflow.py

Closes [CH-55](https://metacell.atlassian.net/browse/CH-55) [CH-61](https://metacell.atlassian.net/browse/CH-61)
Added a parameter to operation tasks that allows us to set a retry policy (defaulted to 10 times), and another parameter that allows to override anything within the task template.
Run a failing task and verify it retries 10 times
[CH-55]: https://metacell.atlassian.net/browse/CH-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CH-61]: https://metacell.atlassian.net/browse/CH-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CH-55 CH-61 add retry policy and customization to tasks

---

infrastructure/common-images/cloudharness-django/libraries/cloudharness-django/cloudharness_django/services/user.py

Closes https://metacell.atlassian.net/browse/CH-221
Same description as https://github.com/MetaCell/cloud-harness/pull/820#issue-3438299550

CH-221 fix: Use kc_id instead of inconsistent kc_username or kc_email for user sync 
